### PR TITLE
Update 1.9.4

### PR DESCRIPTION
**Pull request by peterpt**
New Version update .
Whats new : 
- Full terminal mode (no zenity GUI)
- No remote shells allowed , only local terminals or remote terminals using a remote desktop
- New way to check for internet connection (1st by hostname , and if fails then by dns ip)
- Fudwin 1.0 implemented (for creating 100% rat fud for windows with Slowbutpowerfull or Powerstager)
- Setup script rebuilded
- Local ipv6 added to fatrat
- Update script rebuilded
- Multiple other bug fixes

Video will be made tomorrow and posted here .
-

### CODE REVIEW

**Comment by peterpt** [comment]
Some little bugs were found during the demonstation of fatrat in the video .
All of them are related to the creation of the msfconsole script after a rat is created .
However these bugs are not affecting the creations of the EXE or apk files .

These 3 bugs will be fixed during this next week .
https://www.youtube.com/watch?v=AhxMV6ttans

**Comment by Screetsec** [comment]
okeeys

**Comment by peterpt** [comment]
Fixed setup.sh script when pops up 2nd time the manual path for searchsploit , even if the 1st time was inputed correctly .
Going to patch master at screetsec .

As soon as i fix the other bugs , i will leave here a note .

**Comment by peterpt** [comment]
Fixed backdoor_apk on creating msfconsole scripts at the end .

**Comment by peterpt** [comment]
Fixed the creation & display of current listeners in /listeners folder

**Pull request merged**
