### PR TITLE
Fatrat update

### PR DESCRIPTION
**Pull request by peterpt**
- Fatrat can now be installed on non pentest distros that do not rely on apt to get its  main tools working (metasploit,backdoor-factory & searchsploit) , if user have these tools installed from git , then fatrat setup.sh will provide user to write the path manually where are those tools installed .

- Fatrat will work with a config.path file to guide itself for the paths of the main tools needed .

- Was created a failsafe protection in setup.sh for original user sources.list , in case user stops the setup script in middle and changes were already made to his main repository list by script .

- Fatrat setup allows user to add a shortcut to /usr/local/sbin system folder , in order to be able to call "fatrat" from anywhere in terminal .

With these changes , fatrat is now able to work in a original kali OS , or a different debian based distro .

### CODE REVIEW

**Comment by peterpt** [comment]
uploaded a video now showing the new changes in thefatrat to youtube .
it can be seen at this link : https://www.youtube.com/watch?v=fw9VHDT3bps

**Comment by Screetsec** [comment]
oke thanks  duede

**Comment by peterpt** [comment]
I am still continuing fixing missed packages that exist on kali , but not on a normal linux distro .
gnome terminal was an example , and just now , i notice that powershell uses upx tool to compress data , witch does not come in a normal debian distribution .
I believe that this is the last missing package , i will make another modification on setup script to check for this tool too .

**Comment by peterpt** [comment]
Added a new video , but this one shows setup script installing all the tools needed automatically on a non pentest distribution , and using kali repo to install the main tools .
I did on my old and slow laptop .
https://www.youtube.com/watch?v=GKpEQrGUem4

**Comment by Screetsec** [comment]
some code error in setup.sh

**Comment by peterpt** [comment]
Well , my friend , do not merge anything for now .
It looks that you made this tool specifically for linux pentest ditros like kali , black box , etc ... witch by default have the basic tools already installed by default and you did not made it for a normal linux distro witch does not have those hack tools in their repository .
Also , i notice that fatrat script does not stop even if there are missing tools .
Also notice that apktool is also needed for ruby script to run the embedapk function .

During this week i will make new changes to my git to check for other tools also needed .
I also notice that you user this tool https://github.com/xc0d3rz/metasploit-apk-embed-payload to implement the backdoor in apk files , however you made some changes in the main ruby script adjusting the temp paths for it to work .

Anyway , dont merge anything until i look more deeply into the main script .
I will let you know when it is finished for you to check it out , if you like the changes then you can merge if you want .

The most changes i am making from start until end is to adapt fatrat to work with any debian based linux distro without any packaging dependencies issues .
Blackarch distro can also use in as long as they apt tool to get the missing packages , but on the long run of fatrat script we could add a subroutine to setup script to detect distro and use the apropriate package install tool to install everything .
In blackarch i believe they use "pacman" .

Well , i will tell you anything when i get all this done .

**Comment by Screetsec** [comment]
okey thanks dude , btw I'm very busy. I don't have time now for create setup.sh ( another pentest os )

when you done , you can tell me for merge this

**Comment by Screetsec** [comment]
i have some idea to create some function for fix the problem , but if you done in setup.sh dong forget to tell me for merge

**Comment by peterpt** [comment]
Ok , everything that was more important to change it is done .
On a pentest distro with all tools already installed , if you run setup.sh , the script will make all the detections until upx compressor , then the script will do an update to kali repositories (in case apktool is needed next) , if apk tool is detected then the script will continue and will prompt only at the end asking you if you want to setup a fatrat shortcut in system path : /usr/local/sbin , if you choose yes , then script create that shortcut script and then you can call fatrat from anywhere in terminal .
In case you dont want that shortcut , then script will end and will give you the message to run fatrat you have to write ./fatrat from install directory .

Along the script running , if setup script do not detect any tool then it will install it automatically from current user repository , except these tools (metasploit , backdoor-factory , searchsploit , apktool) , this happens because these tools are pentest tools that are only available in pentest repositories and not on normal repositories like debian or fedora or etc .... , these tools can only be found in kali repo , blackarch , etc ... .
When the script detects that (metasploit , backdoor-factory & searchsploit ) is missing , it will prompt you if you want to setup manually the paths of these 3 tools , it is like this because many people may have these tools cloned from git and they are not set on a system path for detection .
When you are prompted , you can choose individually to setup path manually or install automatically from kali repo , if you choose automatically then the script will get those tools from kali repo and will add automatically their shortcuts to the new config file automatically .
This process will work this way only for these 3 tools .
Apktool is the only tool that the script will install automatically from kali repo without prompting user , this happens because almost no one have this tool cloned from git , usually people get this tool from their apt repository .

But in future , if people from non pentest distros request this option to be added manually too , then we can add it easily . Until that time arrives , it will stay this way .

I test out both scripts here in a full tools apt installed OS , everything went smoothly , and i tested also on a system that requires user input for those tools , everything worked perfect too .
I also run fatrat script and everything was detected perfectly and script run fine .

Check for yourself if you get some error , right here i did not found any .

After the merge , we need maybe to update the readme file and probably the version of fatrat , in case you think is needed .

**Comment by peterpt** [comment]
latest changes on powerfull.sh

https://s4.postimg.org/tq3yu0wal/Desktop_014.png

**Comment by peterpt** [comment]
I already made so many changes in the repository that the best way to clean everything up is to delete my own repository , clone again your repository , and then add all the new changes in 1 single commit .
This way it will be easier for us both to control future changes , and it will better for me to be organized .
I will delete my current repo , and will clone again from yours , then i will make the changes and finally i will pull a new request to you .

**Pull request closed without merging**
